title: "[Idea] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Share an idea for improving the repository, adding new content, or exploring new aspects of simulation theory.
  - type: textarea
    id: idea
    attributes:
      label: Idea Description
      description: Describe your idea in detail.
      placeholder: My idea is...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you think this would be valuable? What problem does it solve or what opportunity does it open?
      placeholder: This would be valuable because...
    validations:
      required: false
