title: "[Q&A] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Ask a question about simulation theory, the content in this repository, or anything related you'd like help understanding.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any additional context or background information that may help answer your question.
      placeholder: Any relevant context, references, or prior research...
    validations:
      required: false
